### ISSUE TITLE
jsp_webshell.py生成的shell访问报错

### ISSUE THREAD

**Issue by Pear1y** [pureqh/webshell#4]
![image](https://user-images.githubusercontent.com/47770089/119972676-1410e680-bfe5-11eb-8763-2672cad11e4c.png)

**Comment by pureqh** [comment]
这是蚁剑的马 想手动连也行 参考菜刀流量base64加密一下就行了


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月28日 18:47:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [pureqh/webshell] jsp_webshell.py生成的shell访问报错 (#4)

**Comment by Pear1y** [comment]
蚁剑连，连接密码默认的zero，还是连接不上呢

**Comment by pureqh** [comment]
麻烦给我看一下截图&nbsp;


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月28日 19:00:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pureqh/webshell] jsp_webshell.py生成的shell访问报错 (#4)




 
蚁剑连，连接密码默认的zero，还是连接不上呢

**Comment by Pear1y** [comment]
![image](https://user-images.githubusercontent.com/47770089/120137921-f2437980-c207-11eb-9076-5d9e2a759e36.png)

**Comment by pureqh** [comment]
你的蚁剑不支持jsp，去装一个支持jsp的分支就行了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月31日(星期一) 中午12:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pureqh/webshell] jsp_webshell.py生成的shell访问报错 (#4)

**Comment by Pear1y** [comment]
get√

**Comment by Pear1y** [comment]
> 你的蚁剑不支持jsp，去装一个支持jsp的分支就行了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年5月31日(星期一) 中午12:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [pureqh/webshell] jsp_webshell.py生成的shell访问报错 (#4) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

已解决，感谢[比心]
